### ISSUE TITLE
Fails to load "parser/ruby20"

### ISSUE THREAD

**Issue by mrdougal** [mrdougal/textmate2-rubocop#1]
Doesn't happen if the bundle is symlinked from ~/Library/Application\ Support/TextMate/Bundles/rubocop.tmbundle to another location on filesystem. (As was the case during development)

Update: vendored gems have their own .gitignore - the missing file (parser/ruby20) is part of that ignore.

**Comment by ghost** [comment]
Please fix soon!

**Comment by mrdougal** [comment]
Should be fixed now, try again @clinton

**Comment by ghost** [comment]
You took your sweet freakin' time, but thanks!
