### ISSUE TITLE
Plugin called me an arsehole

### ISSUE THREAD

**Issue by ghost** [mrdougal/textmate2-rubocop#5]
In the rubocop output I thought I saw the word 'arsehole' out of the corner of my eye. When I focused on the output the word was gone.

Cannot reproduce. Please fix.

**Comment by mrdougal** [comment]
Do you need it to call you an arsehole all the time, or just some of the time? 
:-)

**Comment by mrdougal** [comment]
i'll close this for now, as i'm also able to reproduce the issue
